### ISSUE TITLE
Format amount of decimals for USD values

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/explorer-ui#105]
Currently we format up to three decimals the usd amounts on the value col for the explorer. Reduce this to two or just one

## Implementation details

- format decimal values for usd amounts
- format usd amount ie: $5.674,1

## Acceptance Criteria

- we have formated usd values and less decimals for them

**Comment by wainola** [comment]
@LyonSsS the url is ready to be reviewed. This is a very small change FYI

**Comment by LyonSsS** [comment]
Tested on mainnet network - QA validate as PASS
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk9ZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d33d906df46b5fba26f88d6376a4486553355443/image.png" alt="image.png" />
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--034a6318d844c5ad154651acd354cc8dd7b5c4f7/image.png" alt="image.png" />
