### ISSUE TITLE
Unable to open link for pending transaction

### ISSUE THREAD

**Issue by tcar121293** [sygmaprotocol/explorer-ui#109]
Unable to open transaction link for pending transaction
## Expected Behavior
We are able to open pending transaction

## Current Behavior
unable to open pending transaction
there is an error in console when trying to open the pending transaction - TypeError: Cannot read properties of undefined (reading 'url')

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by MakMuftic** [comment]
Closing in favor of issue: https://github.com/sygmaprotocol/explorer-ui/issues/67
