### ISSUE TITLE
Use loader animation on changing pages of Explorer

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/explorer-ui#119]
Currently, we are only using a loader animation on the initial opening of the explorer. For switching between pages we show this text as shown below :point_down: 
![image](https://github.com/sygmaprotocol/explorer-ui/assets/23664028/53ae8d8b-61d5-466a-aeb8-6eebbb63d6d7)
We should also use the same loader when switching between pages.

## Implementation details

Use a loader animation when switching between pages.

## Testing details

- [ ] Manually confirm that loader animation is being used when switching between pages

## Acceptance Criteria

- [ ] Loader animation shown when changing pages on explorer

**Comment by wainola** [comment]
Aditional notes: currently there is no clear way to check transition from one page to another, since API is taking some ms to return the data. So whenever we click on next page, old data still there, then there is a blink on the screen and the new data is loaded.

**Comment by MakMuftic** [comment]
Resolved by #137
