### ISSUE TITLE
Display USDC fees for USDC transfers from Substrate to EVM

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/explorer-ui#146]
## Short Context

When transferring sygUSDC token from Rhala to Goerli, the displayed fee on test explorer is set to PHA tokens and 12 decimals. 
On chain it is actually sygUSDC token and 6 decimals ( as the token is defined) 
![image](https://github.com/sygmaprotocol/explorer-ui/assets/30255634/de211637-3c85-478b-b61e-d655bf9cd6b0)
![image](https://github.com/sygmaprotocol/explorer-ui/assets/30255634/0e1d6271-4031-4f2f-9df6-0ad3dfb01578)

## Preconditions

1.
2.

## Steps to Reproduce

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by wainola** [comment]
Update: waiting for this [issue](https://github.com/sygmaprotocol/sygma-explorer-indexer/issues/167) to be merged in order to tackle this with complete solution

**Comment by LyonSsS** [comment]
tested on PR branch - > 
<img width="1731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b88c0b064f4b1af7e0df0968efa6925f56358279/image.png" alt="image.png" />
the issue is now fixed
NOTE: sygUSDC decimals is set tyo 18 on evm ( which is not correct) and ui is set to evaluate with  6 decimals as substrate. 
The same 6 decimals for USDC is going to be when we go to mainnet.
