### ISSUE TITLE
Direct link to details of a transfer from Sygma Scan, is not loaded if it comes from a third party

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/explorer-ui#154]
**Context**: If using the direct link to a transfer detail from https://scan.test.buildwithsygma.com/, it is not going to load, if this link is not clicked directly from the home page. 
Ex: https://scan.test.buildwithsygma.com/transfer/0xd60d12e931c0d5faf445b97680c92120fe3eed66ca5d492de34bd04e1ddecff1 
![image](https://github.com/sygmaprotocol/sygma-ui/assets/30255634/2f5d2fb4-39ca-4eed-afde-057f11350ebd)

**Comment by wainola** [comment]
@LyonSsS in the PR is the URL where you can test this 😄

**Comment by LyonSsS** [comment]
Verified on PR link preview by opening out of context links on firefox, opera and chrome incognito - all worked fine 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed1a4c9f76276d66f7deb20fa70e5ba7f1688501/image.png" alt="image.png" />
