### ISSUE TITLE
Showing fungible instead of nonfungible type

### ISSUE THREAD

**Issue by tcar121293** [sygmaprotocol/explorer-ui#158]
Showing fungible instead of nonfungible type

## Short Context
When we bridge nonfungible token, the UI is showing fungible instead of nonfungible
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3R5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1d5110d0ed282525a34b20efa01133fc81a3a5f/fungerr.png" alt="fungerr.png" />

## Preconditions

1.
2.

## Steps to Reproduce

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by wainola** [comment]
note: if transfer is non fungible, remove amount

**Comment by wainola** [comment]
@LyonSsS you can review the change on the url thats provided in the PR thats attached to this issue
