### ISSUE TITLE
Add from and to to transfer detail

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/explorer-ui#51]
We are missing from and to destination in transaction detail page.

**Comment by MakMuftic** [comment]
@mpetrun5 can you explain on what exactly are you referring to. Current deployed explorer UI has these properties in detailed view.

**Comment by mpetrun5** [comment]
Oops. 
To clarify it a bit.
We should have from and to networks (from: Khala to: Rhala) in the detail view (as we have in the list) IMO.
