### ISSUE TITLE
Time formating

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/explorer-ui#53]
We should use some library for time (last I remember Moment does this but it might be outdated by this point) to have formatted time on transfers (5 minutes ago, 1month ago...)

## Implementation details

Transfer list should just have formmated time and the transfer detail should have full time and date.
Etherscan for example 
Detail: https://etherscan.io/tx/0xa6dbae65d8a5383aa9846fdb12009928098f615359ad1595e709672e2a172e57
List https://etherscan.io/token/0x6c5ba91642f10282b576d91922ae6448c9d52f4e?a=0x4038d6a58d58d2560554cf82002cde9cfaab0db1

**Comment by wainola** [comment]
We are using`day.js`, I will fix formatting on detail view. About emulating on what's etherscan, makes sense and it seems to be the standard
