### ISSUE TITLE
Fees missing for substrate detail 

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/explorer-ui#56]
Substrate detail is missing fee information (hardcode 50PHA).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by MakMuftic** [comment]
This is issue for indexer as it is not recording fee when deposit is happening on substrate side.
