### ISSUE TITLE
USD value on value column

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/explorer-ui#60]
## Implementation details

- Display USD value from API responde on the value column. Follow design present in [issue](https://github.com/sygmaprotocol/sygma-explorer-indexer/issues/92)

**Comment by itsbobbyzzz168** [comment]
https://www.figma.com/file/fNeWCeNeOylnvS5UdFD8CY/Sygma-UI?type=design&node-id=931-3592&mode=design&t=TUuAYWHZdx9kiLC7-0 

![Wallet Connected](https://github.com/sygmaprotocol/explorer-ui/assets/134932101/d637cf1b-a366-4c19-b5ec-9e42079f93b7)
