### ISSUE TITLE
Opening links fails

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/explorer-ui#67]
Sometimes opens links for transfer detail fails.
Example: https://scan.buildwithsygma.com/transfer/0x03493d5b1bc12ecd4a3d6782087abdfc726527e734980403bfa4114590452b8c

## Steps to Reproduce (for bugs)

1. Open a fresh browser
2. Click on link

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by wainola** [comment]
Update: for fresh browser, there is no shared config state. I will add a fallback to this, so it doesn't fail. I didn't this use case.

FYI: this issues will be solved if we have SSR and not an SPA

**Comment by itsbobbyzzz168** [comment]
@wainola just checking if this been resolved as part of [Unable to open link for pending transaction #109 ](https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/explorer-ui/109) which has been resolved (above)

**Comment by wainola** [comment]
> @wainola just checking if this been resolved as part of [Unable to open link for pending transaction #109 ](https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/explorer-ui/109) which has been resolved (above)

@itsbobbyzzz168 it is resolved except if you try to open the link on private mode.

**Comment by MakMuftic** [comment]
I will consider this resolved for now
